FROM golang:1.25-bookworm AS builder

WORKDIR /go/src/github.com/emmanuelgautier/domain-scout

COPY go.mod go.mod
COPY go.sum go.sum

ENV CGO_ENABLED 0
ENV GO111MODULE on

RUN go mod download

COPY . .

RUN go build -o /usr/bin/domain-scout .

FROM gcr.io/distroless/static-debian12:nonroot AS runner

COPY --from=builder --chown=nonroot:nonroot /usr/bin/domain-scout /usr/bin/domain-scout

ENTRYPOINT ["domain-scout"]
CMD ["domain-scout"]
